# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20171122_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='portrait',
            field=models.ImageField(default='/static/img/man-235.png', upload_to='speaker_portraits/'),
        ),
    ]
