# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_token', models.CharField(max_length=200)),
                ('update_freq', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
