# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20171106_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('app_id', models.CharField(max_length=400)),
                ('app_secret', models.CharField(max_length=400)),
            ],
        ),
    ]
