# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20171122_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(verbose_name='date organised'),
        ),
    ]
