# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('site_address', models.URLField(max_length=400)),
                ('logo', models.ImageField(upload_to=b'')),
                ('is_partner', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='speaker',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Organisation'),
        ),
    ]
