# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20171122_0132'),
        ('contacts', '0003_auto_20171106_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='role',
            field=models.CharField(blank=True, choices=[('KN', 'Keynote speaker'), ('PA', 'Panelist'), ('DM', 'Demo presenter')], max_length=2),
        ),
        migrations.AddField(
            model_name='speaker',
            name='title',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, upload_to='organisation_logos/'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='site_address',
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='introduction',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='portrait',
            field=models.ImageField(default='/home/oqgpo/projects/HelTechDesignCourse/server/static/img/man-235.png', upload_to='speaker_portraits/'),
        ),
    ]
