# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20171122_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='events.Event'),
        ),
    ]
