# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20171122_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
