# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('date_organised', models.DateTimeField(verbose_name='date organised')),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
    ]
