# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventworker_page_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventworker',
            name='ll_expires',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='eventworker',
            name='user_ll_token',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
