# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20171108_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_organised',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='event',
            name='eid',
            field=models.CharField(default=11, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='programme',
            field=models.TextField(default='default', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default='2017-11-06T18:00:00+0200', verbose_name='date organised'),
            preserve_default=False,
        ),
    ]
