"""
Django settings for heltech project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'h_u7uq$+0tup%)kv-jm72xl3!s6acy&1q&8o#--n61r@^9sl=='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['shapemeal.cs.hut.fi', 'shapemeal.aalto.fi']


# Application definition

INSTALLED_APPS = [
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cron',
    'rest_framework',
    'events',
    'contacts',
    'api',
]

CRON_CLASSES = ['events.tasks.FB']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'heltech.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR+'/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'heltech.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'heltech',
        'USER': 'heltech_devel',
        'PASSWORD': 'De4Hel1Vel2Tech3!!',
        'HOST': 'localhost',
        'PORT': ''
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Helsinki'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/heltech/'
STATIC_ROOT = '/var/www/static/heltech'

MEDIA_ROOT = '/var/www/media/heltech'
MEDIA_URL = '/media/heltech/'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

USE_X_FORWARDED_HOST = True
FORCE_SCRIPT_NAME = "/heltech"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file_django': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/var/lib/jenkins/host/logs/debug.log',
        },
        'file_events': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/var/lib/jenkins/host/logs/debug_events.log',
        },
        'file_contacts': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/var/lib/jenkins/host/logs/debug_contacts.log',
        },
        'file_tasks': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/var/lib/jenkins/host/logs/debug_tasks.log',
        },
        'file_cron': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/var/lib/jenkins/host/logs/debug_cron.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file_django'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'events': {
            'handlers': ['file_events'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'contacts': {
            'handlers': ['file_contacts'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'tasks': {
            'handlers': ['file_tasks'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django_cron': {
            'handlers': ['django_cron'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
